// <auto-generated />
namespace CollectedCompany.Migrations.Shared
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductDatabaseDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductDatabaseDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201605261716159_ProductDatabaseDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
