// <auto-generated />
namespace CollectedCompany.Migrations.Application
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductInformationFKFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductInformationFKFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201605261949200_ProductInformationFKFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
