// <auto-generated />
namespace CollectedCompany.Migrations.Application
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ImageUrlToTemplates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageUrlToTemplates));
        
        string IMigrationMetadata.Id
        {
            get { return "201606162049359_ImageUrlToTemplates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
